### ISSUE TITLE
AREMI 2017-04-24 pre-release test - Layer opens on second attempt

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#95] opened 2017-05-02 05:56 UTC
Layer: Topography/Elevation/Contours

Issue:
- Displays error on first attempt
- Opens normally on second attempt
- Tried a number of times with and without using the 'aremi.json' file supplied by Mats on 1/5/17 - same result.

**Comment by meh9** [comment] 2017-05-03 01:54
Interesting! This looks like an existing Terria issue (it's already in the production version), so I'm logging a ticket there.

Steps to reproduce:
# Navigate catalogue to Topography/Elevation but DO NOT click on the Contours layer - once the preview has loaded the bog does not occur.
# Click the `+` button to add the layer to the map without having seen the layer as a preview.

**Comment by meh9** [comment] 2017-05-03 02:01
Have logged TerriaJS/terriajs#2501.

**Comment by meh9** [comment] 2017-05-04 00:31
This has now been fixed in TerriaJS.

**Closed by meh9** 2017-05-04 00:31 UTC
Labels: GA-testing, TerriaJS
