### ISSUE TITLE
Messy label of Feedback form when expandable textbox is expanded to the right

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/aremi-natmap#71] opened 2017-02-24 00:54 UTC
If you resize the textbox of the feedback form towards the right the position of its label goes out of place on the and stays out of place.

**Comment by meh9** [comment] 2017-04-20 07:46
I believe this is fixed now. Please submit screenshots in future to show exactly what the problem is.

**Closed by meh9** 2017-04-20 07:46 UTC
